spring.application.name=arcticblue
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/arcticblue}
spring.datasource.username=${DB_USERNAME:your_postgres_username}
spring.datasource.password=${DB_PASSWORD:your_postgres_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.jackson.default-property-inclusion=non_null
